CREATE TABLE "accouchements" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"grossesse_id" uuid NOT NULL,
	"patient_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"date_accouchement" timestamp NOT NULL,
	"lieu_accouchement" text,
	"terme_semaines" integer,
	"terme_jours" integer,
	"date_debut_travail" timestamp,
	"duree_travail_heures" integer,
	"duree_travail_minutes" integer,
	"rupture_membranes" text,
	"date_rupture_membranes" timestamp,
	"aspect_liquide_amniotique" text,
	"apd" boolean DEFAULT false,
	"date_apd" timestamp,
	"autre_analgesie" text,
	"mode_accouchement" text NOT NULL,
	"type_instrumental" text,
	"indication_instrumental" text,
	"indication_cesarienne" text,
	"presentation" text,
	"variete" text,
	"perinee" text,
	"degre" text,
	"suture" boolean,
	"type_fil_suture" text,
	"type_delivrance" text,
	"duree_delivrance_minutes" integer,
	"placenta_complet" boolean,
	"poids_placenta" integer,
	"anomalies_placenta" text,
	"perte_sanguine" integer,
	"hemorragie" boolean DEFAULT false,
	"traitement_hemorragie" text,
	"examen_post_partum" text,
	"complications" text,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "accouchements" ADD CONSTRAINT "accouchements_grossesse_id_grossesses_id_fk" FOREIGN KEY ("grossesse_id") REFERENCES "public"."grossesses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accouchements" ADD CONSTRAINT "accouchements_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accouchements" ADD CONSTRAINT "accouchements_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;